<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('business_information', function (Blueprint $table) {
            $table->id();
            $table->text('coverage_info')->nullable();
            $table->text('month_business_salt')->nullable();
            $table->text('month_business_flour')->nullable();
            $table->text('month_business_oil')->nullable();
            $table->text('month_business_rice')->nullable();
            $table->text('month_business_pulse')->nullable();
            $table->text('month_business_tea')->nullable();
            $table->text('month_business_dairy')->nullable();
            $table->text('month_business')->nullable();
            $table->text('comm_earnings')->nullable();
            $table->text('vehicle_prod')->nullable();
            $table->text('sr_productivity')->nullable();
            $table->text('urban_wetmarket_grocer')->nullable();
            $table->text('urban_neighborhood_grocer')->nullable();
            $table->text('urban_general_store')->nullable();
            $table->text('urban_cosmetic_store')->nullable();
            $table->text('confectionary')->nullable();
            $table->text('urban_retail_coverage')->nullable();
            $table->text('smmt')->nullable();
            $table->text('chemist_pharmacy')->nullable();
            $table->text('rural_grocer')->nullable();
            $table->text('tong_tea_stall')->nullable();
            $table->text('horeca')->nullable();
            $table->text('rural_retail_coverage')->nullable();
            $table->text('dd_institution')->nullable();
            $table->text('others_channel')->nullable();
            $table->text('route_wholesale')->nullable();
            $table->text('csm_route_ols')->nullable();
            $table->text('sd_coverage_ols')->nullable();
            $table->text('alt_coverage')->nullable();
            $table->text('direct_coverage')->nullable();
            $table->text('controlled_coverage')->nullable();
            $table->integer('daily_total_routes')->nullable();
            $table->integer('bi_weekly_3_total_routes')->nullable();
            $table->integer('bi_weekly_2_total_routes')->nullable();
            $table->integer('weekly_total_routes')->nullable();
            $table->integer('fortnightly_total_routes')->nullable();
            $table->integer('daily_total_sections')->nullable();
            $table->integer('bi_weekly_3_total_sections')->nullable();
            $table->integer('bi_weekly_2_total_sections')->nullable();
            $table->integer('weekly_total_sections')->nullable();
            $table->integer('fortnightly_total_sections')->nullable();
            $table->text('peripheral_db_east')->nullable();
            $table->text('peripheral_db_west')->nullable();
            $table->text('peripheral_db_north')->nullable();
            $table->text('peripheral_db_south')->nullable();
            $table->text('peripheral_md_east')->nullable();
            $table->text('peripheral_md_west')->nullable();
            $table->text('peripheral_md_north')->nullable();
            $table->text('peripheral_md_south')->nullable();
            $table->text('back_office_team_manager')->nullable();
            $table->text('back_office_team_supervisor')->nullable();
            $table->text('back_office_team_comp_operator')->nullable();
            $table->text('back_office_team_csm')->nullable();
            $table->text('back_office_team_office_clerk')->nullable();
            $table->text('back_office_team_godown_keeper')->nullable();
            $table->text('back_office_team_peon_guards')->nullable();
            $table->text('back_office_team_driver_nmv')->nullable();
            $table->text('back_office_team_others')->nullable();
            $table->text('back_office_team_field_forces')->nullable();
            $table->text('back_office_team_sales_representative')->nullable();
            $table->text('back_office_team_delivery_man')->nullable();
            $table->text('back_office_team_driver_mech_vehicle')->nullable();
            $table->text('back_office_force')->nullable();
            $table->text('total_manpower')->nullable();
            $table->text('logistics_vehicles')->nullable();
            $table->text('logistics_number_of_mv_4wh')->nullable();
            $table->text('logistics_tempoo_3whl')->nullable();
            $table->text('logistics_engine_boat_mv')->nullable();
            $table->text('logistics_number_of_nmv')->nullable();
            $table->text('logistics_total_vehicles')->nullable();
            $table->text('logistics_vehicle_section')->nullable();
            $table->text('logistics_ol_productivity')->nullable();
            $table->text('logistics_route_prod')->nullable();
            $table->text('logistics_section_prod')->nullable();
            $table->text('logistics_route')->nullable();
            $table->text('route_service_mv_route')->nullable();
            $table->text('route_service_nmv_route')->nullable();
            $table->text('outlet_coverage_mv_route')->nullable();
            $table->text('outlet_coverage_nmv_route')->nullable();
            $table->text('route_productivity_mv_route')->nullable();
            $table->text('route_productivity_nmv_route')->nullable();
            $table->integer('total_routes')->nullable();
            $table->text('leverage_it')->nullable();
            $table->text('computer')->nullable();
            $table->text('printer')->nullable();
            $table->text('warehouse_address')->nullable();
            $table->text('warehouse_district')->nullable();
            $table->text('warehouse_thana')->nullable();
            $table->text('office_hight')->nullable();
            $table->text('warehouse_hight')->nullable();
            $table->text('hight_total')->nullable();
            $table->text('office_length')->nullable();
            $table->text('warehouse_length')->nullable();
            $table->text('length_total')->nullable();
            $table->text('workspace_structure_office')->nullable();
            $table->text('warehouse_structure_length')->nullable();
            $table->text('warehouse_condition')->nullable();
            $table->text('electrical_wiring')->nullable();
            $table->text('insurance_coverage')->nullable();
            $table->text('insurance_coverage_office')->nullable();
            $table->text('insurance_coverage_warehouse')->nullable();
            $table->text('team_sitting_arrangement')->nullable();
            $table->text('fire_fighting_facilities')->nullable();
            $table->text('investment_capabilities')->nullable();
            $table->text('self_finance')->nullable();
            $table->text('loan')->nullable();
            $table->text('working_capital')->nullable();
            $table->text('stock_value')->nullable();
            $table->text('credit_to_trade')->nullable();
            $table->text('cash_in_hand')->nullable();
            $table->text('pending_claims')->nullable();
            $table->text('mechanized_vehicle')->nullable();
            $table->text('non_mechanized_vehicle')->nullable();
            $table->text('office_furniture_equipment')->nullable();
            $table->text('total_investment')->nullable();
            $table->text('wc_to')->nullable();
            $table->text('stock_days_cover')->nullable();
            $table->text('stock_salt')->nullable();
            $table->text('stock_flour')->nullable();
            $table->text('stock_oil')->nullable();
            $table->text('stock_rice')->nullable();
            $table->text('stock_pulse')->nullable();
            $table->text('stock_tea')->nullable();
            $table->text('stock_dairy')->nullable();
            $table->text('investment_stock')->nullable();
            $table->text('investment_to')->nullable();
            $table->text('distributor_bank_name')->nullable();
            $table->text('bank_account_number')->nullable();
            $table->text('branch_name')->nullable();
            $table->text('payment_mode')->nullable();
            $table->text('delivery_product')->nullable();
            $table->text('carrying_charge_claimable')->nullable();
            $table->unsignedBigInteger('created_by')->nullable();
            $table->unsignedBigInteger('updated_by')->nullable();
            $table->foreign('created_by')->references('id')->on('users')->onDelete('cascade');
            $table->foreign('updated_by')->references('id')->on('users')->onDelete('cascade');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('business_information');
    }
};
